---
dist: bionic
language: rust
rust: [stable, beta, nightly]

cache:
  cargo: true

before_install:
  - cargo install --force cargo-audit
  - cargo generate-lockfile

script:
  - cargo audit
  - cargo test --verbose --all
  - cargo build --verbose --all

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
    on_failure: never