---
dist: trusty
language: rust
rust: [stable, beta, nightly]

cache:
  cargo: true

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
    on_failure: always
