#!/usr/bin/env python3.5

import argparse
import json

from mutagen.mp3 import MP3
from pathlib import Path


def main():
    """Main entrypoint."""
    parser = argparse.ArgumentParser()
    args = parser.parse_args()

    results = {}

    for f in Path("test/fixtures/id3").glob("*.mp3"):
        m = MP3(str(f))
        if m.tags:
            results[str(f)] = { t.FrameID: t.text for t in [m.tags[k] for k in m.tags.keys()] }

    print(json.dumps(results, indent=2, sort_keys=True))

if __name__ == "__main__":
    main()
